In [1]:
#import all necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import imageio
import numpy.matlib
import os

In [2]:
# read the data set
nodes = pd.read_csv('/Users/lars-manuelschneider/Downloads/data/nodes.txt', delimiter= "\t", header=None)
nodes.columns = ["useless", "Blog", "Polit_Orientation", "dont_Know"]
nodes

useless                            Blog  Polit_Orientation  \
0           1            100monkeystyping.com                  0   
1           2      12thharmonic.com/wordpress                  0   
2           3           40ozblog.blogspot.com                  0   
3           4                 4lina.tblog.com                  0   
4           5           750volts.blogspot.com                  0   
...       ...                             ...                ...   
1485     1486  youngconservative.blogspot.com                  1   
1486     1487                zebrax.blogs.com                  1   
1487     1488             zeke01.blogspot.com                  1   
1488     1489              zeke01.typepad.com                  1   
1489     1490          zeph1z.tripod.com/blog                  1   

                  dont_Know  
0                 Blogarama  
1               BlogCatalog  
2     Blogarama,BlogCatalog  
3                 Blogarama  
4                 Blogarama  
...                     ...  
1485              Blogarama  
1486            BlogCatalog  
1487  Blogarama,BlogCatalog  
1488              Blogarama  
1489              Blogarama  

[1490 rows x 4 columns]

In [3]:
#nodes = nodes.drop(columns=nodes.columns[0])

In [4]:
edges = pd.read_csv('/Users/lars-manuelschneider/Downloads/data/edges.txt', delimiter= "\t", header=None)
edges

0     1
0       267  1394
1       267   483
2       267  1051
3       904  1479
4       904   919
...     ...   ...
19085  1133  1390
19086  1133  1429
19087  1133  1423
19088  1133  1408
19089  1133  1152

[19090 rows x 2 columns]

In [5]:
#edges = edges.to_numpy()

In [6]:
edges

0     1
0       267  1394
1       267   483
2       267  1051
3       904  1479
4       904   919
...     ...   ...
19085  1133  1390
19086  1133  1429
19087  1133  1423
19088  1133  1408
19089  1133  1152

[19090 rows x 2 columns]

In [7]:
cluster = 2

In [8]:
r = np.ones((edges.shape[0],1)).flatten()

In [9]:
s = len(nodes)

In [10]:
n = 1490
A = np.zeros((n,n))
edges_array = np.array(edges)
for i in edges_array:
    if i[0] != i[1]:
        A[i[0]-1][i[1]-1] = 1
        A[i[1]-1][i[0]-1] = 1

A_sum = np.sum(A, axis = 1)

In [11]:
A[1489]

array([0., 0., 0., ..., 0., 0., 0.])

In [12]:
# now we need to get rid of all the isolated nodes, basically all the values when the row sum equals zero
test = np.sum(A, axis=1)
test
np.count_nonzero(test)

1224

In [13]:
isolated_nodes = np.where(A_sum == 0)[0]

In [14]:
isolated_nodes

array([   2,    3,   24,   47,   48,   49,   53,   56,   59,   60,   62,
         70,   73,   90,   93,  107,  110,  111,  119,  121,  125,  130,
        133,  134,  138,  145,  147,  152,  160,  163,  168,  173,  175,
        182,  194,  195,  196,  198,  205,  213,  220,  225,  227,  230,
        231,  233,  235,  239,  241,  246,  250,  253,  257,  259,  260,
        262,  264,  265,  269,  270,  284,  285,  293,  301,  303,  305,
        318,  319,  321,  323,  329,  333,  335,  338,  341,  342,  345,
        347,  358,  365,  368,  371,  374,  375,  385,  394,  397,  411,
        412,  422,  424,  429,  432,  434,  446,  454,  455,  456,  457,
        458,  462,  463,  472,  475,  477,  481,  484,  485,  509,  519,
        521,  525,  527,  528,  530,  532,  544,  545,  551,  556,  557,
        564,  568,  570,  575,  580,  581,  585,  591,  592,  593,  598,
        605,  606,  607,  610,  626,  628,  629,  632,  635,  637,  638,
        655,  657,  662,  664,  671,  672,  677,  6

In [15]:
A_new= np.delete(A, isolated_nodes, axis=1)
A_new = np.delete(A_new,isolated_nodes, axis=0)

In [16]:
len(A_new)

1224

In [17]:
A_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
D = np.diag(np.sum(A_new, axis =1))

In [19]:
D

array([[26.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., 45.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  4., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., 18.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [20]:
L = D-A_new

In [21]:
L

array([[26., -1.,  0., ...,  0.,  0.,  0.],
       [-1., 45.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  4., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ..., -1., 18.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [83]:
# now compute the k eigenvectors of the graph Laplacian
from numpy import linalg as LA
w,v = LA.eigh(L) # w is the eigenvalue and v is the eigenvector


In [84]:
v

array([[ 6.29588866e-20, -2.86064784e-02, -1.58866314e-03, ...,
         4.69059623e-05, -1.50028327e-04,  2.86881278e-03],
       [-2.14297930e-17, -2.86064784e-02, -1.59180448e-03, ...,
         3.75933956e-05, -2.04648011e-04,  2.90496915e-03],
       [ 5.17969544e-16, -2.86064784e-02, -1.72488028e-03, ...,
        -1.86848086e-05, -4.60539729e-05, -1.48941553e-05],
       ...,
       [-3.97228535e-16, -2.86064784e-02, -1.88647150e-03, ...,
        -1.11631244e-05, -5.99068988e-07, -3.04397639e-08],
       [ 1.98783727e-17, -2.86064784e-02, -1.56823977e-03, ...,
         3.36044426e-03,  1.83392984e-04,  1.06857486e-05],
       [-5.26394313e-16, -2.86064784e-02, -1.91584569e-03, ...,
         1.05672450e-06,  1.04750618e-06,  1.67197840e-07]])

In [73]:
v[:,0:2]

array([[ 6.29588866e-20, -2.86064784e-02],
       [-2.14297930e-17, -2.86064784e-02],
       [ 5.17969544e-16, -2.86064784e-02],
       ...,
       [-3.97228535e-16, -2.86064784e-02],
       [ 1.98783727e-17, -2.86064784e-02],
       [-5.26394313e-16, -2.86064784e-02]])

In [85]:
# depending on the amount of clusters I am keeping the amount of eigenvectors
v = v[:,0:6]

In [25]:
np.shape(v)

(1224, 3)

In [26]:
# check if there is any nan value in the array
np.argwhere(np.isnan(v))

array([], shape=(0, 2), dtype=int64)

In [86]:
# last step is running k-means from task 3 with the new data
iter = 20
in_centroids = initial_centroids(v,cluster)
idx, centroids = k_means(v, in_centroids, iter)


In [33]:
len(idx)

1224

In [34]:
min(idx)

0.0

In [35]:
np.shape(centroids)

(2, 3)

In [36]:
np.shape(idx)

(1224,)

In [37]:
nodes = nodes.to_numpy()

In [38]:
nodes

array([[1, '100monkeystyping.com', 0, 'Blogarama'],
       [2, '12thharmonic.com/wordpress', 0, 'BlogCatalog'],
       [3, '40ozblog.blogspot.com', 0, 'Blogarama,BlogCatalog'],
       ...,
       [1488, 'zeke01.blogspot.com', 1, 'Blogarama,BlogCatalog'],
       [1489, 'zeke01.typepad.com', 1, 'Blogarama'],
       [1490, 'zeph1z.tripod.com/blog', 1, 'Blogarama']], dtype=object)

In [39]:
for i in range (len(nodes)):
    nodes[i][0] = i
nodes[:,0]

array([0, 1, 2, ..., 1487, 1488, 1489], dtype=object)

In [40]:
nodes

array([[0, '100monkeystyping.com', 0, 'Blogarama'],
       [1, '12thharmonic.com/wordpress', 0, 'BlogCatalog'],
       [2, '40ozblog.blogspot.com', 0, 'Blogarama,BlogCatalog'],
       ...,
       [1487, 'zeke01.blogspot.com', 1, 'Blogarama,BlogCatalog'],
       [1488, 'zeke01.typepad.com', 1, 'Blogarama'],
       [1489, 'zeph1z.tripod.com/blog', 1, 'Blogarama']], dtype=object)

In [41]:
nodes = np.delete(nodes, isolated_nodes,0)

In [42]:
isolated_nodes

array([   2,    3,   24,   47,   48,   49,   53,   56,   59,   60,   62,
         70,   73,   90,   93,  107,  110,  111,  119,  121,  125,  130,
        133,  134,  138,  145,  147,  152,  160,  163,  168,  173,  175,
        182,  194,  195,  196,  198,  205,  213,  220,  225,  227,  230,
        231,  233,  235,  239,  241,  246,  250,  253,  257,  259,  260,
        262,  264,  265,  269,  270,  284,  285,  293,  301,  303,  305,
        318,  319,  321,  323,  329,  333,  335,  338,  341,  342,  345,
        347,  358,  365,  368,  371,  374,  375,  385,  394,  397,  411,
        412,  422,  424,  429,  432,  434,  446,  454,  455,  456,  457,
        458,  462,  463,  472,  475,  477,  481,  484,  485,  509,  519,
        521,  525,  527,  528,  530,  532,  544,  545,  551,  556,  557,
        564,  568,  570,  575,  580,  581,  585,  591,  592,  593,  598,
        605,  606,  607,  610,  626,  628,  629,  632,  635,  637,  638,
        655,  657,  662,  664,  671,  672,  677,  6

In [43]:
nodes

array([[0, '100monkeystyping.com', 0, 'Blogarama'],
       [1, '12thharmonic.com/wordpress', 0, 'BlogCatalog'],
       [4, '750volts.blogspot.com', 0, 'Blogarama'],
       ...,
       [1487, 'zeke01.blogspot.com', 1, 'Blogarama,BlogCatalog'],
       [1488, 'zeke01.typepad.com', 1, 'Blogarama'],
       [1489, 'zeph1z.tripod.com/blog', 1, 'Blogarama']], dtype=object)

In [44]:
counter_0 = 0
for f in range(len(nodes)):
    if (nodes[f][2] == 0):
        counter_0 = counter_0 + 1

In [45]:
counter_0

588

In [46]:
counter_1 = len(nodes)-counter_0

In [47]:
counter_1

636

In [87]:
mismatch_0 = 0


for i in range(len(nodes)):
    if ((nodes[i][2] != idx[i])) and (nodes[i][2] == 0):
        mismatch_0 = mismatch_0 +1

In [88]:
false_class_0 = mismatch_0/counter_0
false_class_0

0.006802721088435374

In [89]:
mismatch_1 = 0


for i in range(len(nodes)):
    if ((nodes[i][2] != idx[i])) and (nodes[i][2] == 0):
        mismatch_1 = mismatch_1 +1

In [90]:
false_class_1 = mismatch_1/counter_1
false_class_1

0.006289308176100629

In [28]:
# create random initial centroids 
def initial_centroids(X, k):
    m,n = X.shape
    centroids = np.zeros((k,n))
    idx = np.random.randint(0,m,k)
    
    for i in range (k):
        centroids[i,:] = X[idx[i],:]
    return centroids

In [29]:
# funtion that is able to find the closest centroid for each instance in
# the data
def closest_centroid(X, centroids):
    ph = np.zeros((len(X)))
    
    
    for i in range(len(X)):
        distance = 99999 #init
        
        for j in range(len(centroids)):
            if np.sum(np.square(abs(X[i,:]-centroids[j,:])))<distance:
                distance=np.sum(np.square(abs(X[i,:]-centroids[j,:])))
                ph[i] = j
    return ph
#, distance

In [30]:
#compute the centroid of a cluster, in the vernacular the centroid is defeined
# as the mean of all data points currently assigned to a certain cluster (different between means and mediods)
def adjust_centroids(X,idx,k):
    m,n = X.shape # number of rows, columns
    centroids=np.zeros((k,n))
    for i in range(0,k):
        temp = idx==i #The result will contain T/F values. 
        temp = temp.astype(int) #Let's change the results to 1 and 0. 1 if the point belong to centroid i, 0 otherwise
        counter = sum(temp); #total number of points. We will use this to calculate the mean of all points
        temp.resize((np.size(X,0),1)) #from array to one long column of ones
        total_matrix = np.matlib.repmat(temp,1,n) #repeat the 1 column three times (RBG)
        temp = np.multiply(X,total_matrix) #filter data to only those belong to centroid i
        centroids[i] = (1/counter)*np.sum(temp,axis=0) #sum each column and divide by total = average.  
    return centroids

In [31]:
def k_means(X, initial_centroids, iter):
    centroids = initial_centroids
    counter = 0
    for i in range(iter):
        #idx, distance = closest_centroid(X, centroids)
        idx = closest_centroid(X, centroids)
        centroids = adjust_centroids(X, idx, len(centroids))
        counter = counter + 1
        #print(counter, distance)
        
    return idx, centroids